<?xml version="1.0" encoding="utf-8"?>
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:fo="http://www.w3.org/1999/XSL/Format">
	<xsl:variable name="initial_bottom_pos">30.5</xsl:variable>
	<xsl:variable name="initial_left_pos">2</xsl:variable>
	<xsl:variable name="height_increment">2cm</xsl:variable>
	<xsl:variable name="width_increment">10cm</xsl:variable>
	<xsl:variable name="frame_height">15cm</xsl:variable>
	<xsl:variable name="frame_width">20cm</xsl:variable>
	<xsl:variable name="number_columns">1</xsl:variable>
	<xsl:variable name="max_frames">30</xsl:variable>
	<xsl:variable name="smallcase" select="'abcdefghijklmnopqrstuvwxyz'" />
	<xsl:variable name="uppercase" select="'ABCDEFGHIJKLMNOPQRSTUVWXYZ'" />
	<xsl:template match="/">
		<xsl:apply-templates select="lots"/>
	</xsl:template>
	<xsl:template match="lots">
		<document>
			<template leftMargin="2.0cm" rightMargin="2.0cm" topMargin="2.0cm" bottomMargin="2.0cm" title="Address list" author="Generated by Open ERP">
				<pageTemplate id="all">
					<pageGraphics/>
					<xsl:apply-templates select="lot-line" mode="frames"/>
				</pageTemplate>
			</template>
			<stylesheet>
				<paraStyle name="nospace" fontName="Courier" fontSize="10" spaceBefore="0" spaceAfter="0"/>
				<blockTableStyle id="mytable">
					<blockAlignment value="CENTER"/>
					<blockValign value="MIDDLE"/>
					<blockFont name="Helvetica-BoldOblique" size="14" />
					<blockFont name="Helvetica" size="8" />
					<lineStyle kind="GRID" colorName="black" tickness="1"/>
				</blockTableStyle>
			</stylesheet>
			<story>
				<xsl:apply-templates select="lot-line" mode="story"/>
			</story>
		</document>
	</xsl:template>
	<xsl:template match="lot-line" mode="frames">
		<xsl:if test="position() &lt; $max_frames">
			<frame>
				<xsl:attribute name="width">
					<xsl:value-of select="$frame_width"/>
				</xsl:attribute>
				<xsl:attribute name="height">
					<xsl:value-of select="$frame_height"/>
				</xsl:attribute>
				<xsl:attribute name="x1">
					<xsl:value-of select="$height_increment"/>
				</xsl:attribute>
				<xsl:attribute name="y1">
					<xsl:value-of select="$width_increment"/>
				</xsl:attribute>
			</frame>
		</xsl:if>
	</xsl:template>
	<xsl:template match="lot-line" mode="story">
		<blockTable style="mytable" colWidths="2.5cm,12cm">
			<tr>
				<td  >
					<barCode>
						<xsl:value-of select="patientid"/>
					</barCode>
				</td>
				<td >
					<para style="nospace">
						Patient ID :
						<xsl:value-of select="patientid"/>
					</para>
					<para style="nospace">
						Title :
						<xsl:value-of select="patienttitle"/>
					</para>
					<para style="nospace">
						Name :
						<xsl:choose>
							<xsl:when test="patientname != ''">
								<xsl:value-of select="patientname"/>
								<xsl:text> </xsl:text>
								<xsl:value-of select="patientmiddlename"/>
								<xsl:text> </xsl:text>
								<xsl:value-of select="patientlastname"/>
							</xsl:when>
							<xsl:otherwise>
								<xsl:value-of select="patientname"/>
							</xsl:otherwise>
						</xsl:choose>
					</para>
					<para style="nospace">
						Gender :
						<xsl:choose>
							<xsl:when test="patientsex ='f' " >
								<xsl:text>F</xsl:text>
							</xsl:when>
						</xsl:choose>
						<xsl:choose>
							<xsl:when test="patientsex ='m' ">
								<xsl:text>M</xsl:text>
							</xsl:when>
						</xsl:choose>
					</para>
					<para style="nospace">
						Date of Birth :
						<xsl:value-of select="dob"/>
					</para>
					<para style="nospace">
						Age :
						<xsl:value-of select="patientage"/>
					</para>
					<para style="nospace">
						Blood Group :
						<xsl:value-of select="translate(bloodtype, $smallcase, $uppercase)"/>
						<xsl:value-of select="rh"/>
					</para>
					<para style="nospace">
						Address :
						<xsl:choose>
							<xsl:when test="patientstreet != ''">
								<xsl:value-of select="patientstreet"/>
								<xsl:text>,</xsl:text>
							</xsl:when>
						</xsl:choose>
						<xsl:choose>
							<xsl:when test="patientstreet2 != ''">
								<xsl:value-of select="patientstreet2"/>
								<xsl:text>,</xsl:text>
							</xsl:when>
						</xsl:choose>

					</para>
					<para style="nospace">
						<xsl:choose>
							<xsl:when test="patientcity != ''">
								<xsl:value-of select="patientcity"/>
								<xsl:text>,</xsl:text>
							</xsl:when>
						</xsl:choose>
						<xsl:choose>
							<xsl:when test="state != ''">
								<xsl:value-of select="state"/>
								<xsl:text>,</xsl:text>
							</xsl:when>
						</xsl:choose>
						<xsl:choose>
							<xsl:when test="country != ''">
								<xsl:value-of select="country"/>
								<xsl:text>,</xsl:text>
							</xsl:when>
						</xsl:choose>
					</para>
					<para style="nospace">
						<xsl:choose>
							<xsl:when test="patientzip != ''">
								<xsl:value-of select="patientzip"/>
								<xsl:text>.</xsl:text>
							</xsl:when>
						</xsl:choose>
					</para>
					<para style="nospace">
						Phone No :
						<xsl:value-of select="phoneno"/>
					</para>
					<para style="nospace">
						Nationality :
						<xsl:value-of select="nationality"/>
					</para>
					<para style="nospace">
						Family Member :
						<xsl:value-of select="familymember"/>
						<xsl:text> </xsl:text>
						<xsl:value-of select="familymemberlast"/>
					</para>

				</td>
			</tr>
		</blockTable>
	</xsl:template>
</xsl:stylesheet>
